Repository AY2021S1-CS2103T-T15-1/tp, pull requests merged in 2020-11, with the labels that each got.

#251 Create list shortcut command
  src/main/java/seedu/address/logic/commands/ListShortcutCommand.java
  src/main/java/seedu/address/logic/commandshortcut/CommandShortcut.java
  src/main/java/seedu/address/logic/commandshortcut/CommandShortcutSet.java
  src/main/java/seedu/address/logic/commandshortcut/CommandWord.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: enhancement

#257 Simplify class diagrams and update documentations
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/list_shortcut.PNG
Labels: documentation

#264 Branch v1.2
  docs/UserGuide.md
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/AppointmentListCard.fxml
  src/main/resources/view/ClientListCard.fxml
  src/main/resources/view/HairdresserListCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
Labels: documentation, type.Task

#268 Fix UML diagram
  ModelClassDiagram.png
  docs/UserGuide.md
  docs/diagrams/CommandShortcutClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/CommandShortcutClassDiagram.png
  src/main/java/seedu/address/logic/commandshortcut/CommandShortcut.java
Labels: bug

#278 Add test for hairdresser and print
  .gitignore
  src/main/java/seedu/address/logic/commands/PrintCommand.java
  src/main/java/seedu/address/model/IdCounter.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/PrintCommandTest.java
  src/test/java/seedu/address/logic/commands/hairdresser/AddHairdresserCommandTest.java
  src/test/java/seedu/address/logic/commands/hairdresser/DeleteHairdresserCommandTest.java
  src/test/java/seedu/address/logic/commands/hairdresser/EditHairdresserCommandTest.java
  src/test/java/seedu/address/logic/commands/hairdresser/FilterHairdresserTest.java
  src/test/java/seedu/address/logic/commands/hairdresser/ListHairdresserCommandTest.java
  src/test/java/seedu/address/logic/commandshortcut/CommandShortcutSetTest.java
  src/test/java/seedu/address/logic/parser/hairdresser/AddHairdresserCommandParserTest.java
  src/test/java/seedu/address/logic/parser/hairdresser/DeleteHairdresserCommandParserTest.java
  src/test/java/seedu/address/logic/parser/hairdresser/EditHairdresserCommandParserTest.java
  src/test/java/seedu/address/logic/parser/hairdresser/FilterHairdresserCommandParserTest.java
  src/test/java/seedu/address/model/specialisation/SpecialisationTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/testutil/EditHairdresserDescriptorBuilder.java
  src/test/java/seedu/address/testutil/HairdresserBuilder.java
  src/test/java/seedu/address/testutil/TypicalClients.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task

#282 PPP james
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/iamjamestan.md
Labels: documentation

#284 Add validation for IdCounter when reading from Json
  src/main/java/seedu/address/storage/JsonSerializableHairStyleX.java
Labels: type.Enhancement

#287 Check number of user input for each prefix in filter_appt method
  README.md
  docs/UserGuide.md
  docs/team/ya0-yuan.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/FilterEntityCommand.java
  src/main/java/seedu/address/logic/commands/client/FilterClientCommand.java
  src/main/java/seedu/address/logic/commands/hairdresser/FilterHairdresserCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/appointment/FilterAppointmentCommandParser.java
  src/main/resources/view/MainWindow.fxml
Labels: bug

#288 Update user guide
  docs/UserGuide.md
  docs/images/ModelClassDiagram.png
  docs/images/shortcut/add_alias_success.png
  docs/images/shortcut/add_shortcut_success.PNG
  docs/images/shortcut/delete_shortcut.PNG
  docs/images/shortcut/deletealias.png
  docs/images/shortcut/list_shortcut.png
  docs/images/shortcut/new_alias.png
  docs/images/shortcut/new_shortcut.PNG
  docs/images/shortcut/use_new_alias.png
  docs/images/shortcut/use_new_shortcut.PNG
Labels: documentation

#290 fix dg
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/FilterCommandSequenceDiagram.png
Labels: documentation

#291 Update PPP
  docs/team/pooty3.md
Labels: documentation

#299 Update DG manual testing instructions for appointment
  docs/DeveloperGuide.md
  docs/team/iamjamestan.md
Labels: documentation

#303 Add Yifan's PPP
  docs/team/theyifan.md
Labels: type.Task

#308 Update manual testing for dev guide
  docs/DeveloperGuide.md
Labels: documentation

#311 Update DG for client section in manual testing
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#318 Yao Yuan's PPP
  docs/team/ya0-yuan.md
Labels: documentation

#319 Fix ug bugs
  docs/UserGuide.md
  docs/team/ya0-yuan.md
  src/main/java/seedu/address/model/tag/Tag.java
Labels: documentation, type.Bug

#328 Update user guide
  docs/UserGuide.md
Labels: documentation

#333 fix ug dg bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FilterClientCommandSequenceDiagram.puml
  docs/diagrams/FindCommandSequenceDiagram.puml
  docs/images/FilterClientCommandSequenceDiagram.png
  docs/images/FilterCommandSequenceDiagram.png
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
Labels: documentation, type.Bug

#334 fix typo in ppp
  docs/team/ya0-yuan.md
Labels: documentation
