Repository AY2021S1-CS2103T-T15-1/tp, pull requests merged in 2020-10, with the labels that each got.

#115 Make hairdresser specialisation optional
  src/main/java/seedu/address/logic/parser/hairdresser/AddHairdresserCommandParser.java
Labels: type.Task

#119 Make List, Edit and Delete for Appointment
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/appointment/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/appointment/EditAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/appointment/ListAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/client/ListClientCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/appointment/DeleteAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/appointment/EditAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/client/DeleteClientCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/appointment/AppointmentStatus.java
  src/main/java/seedu/address/storage/JsonAdaptedAppointment.java
Labels: type.Task

#125 Change appointment parser to take in index instead of ID
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/appointment/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/appointment/EditAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/client/EditClientCommand.java
  src/main/java/seedu/address/logic/commands/hairdresser/AddHairdresserCommand.java
  src/main/java/seedu/address/logic/commands/hairdresser/EditHairdresserCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/appointment/AddAppointmentCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/FutureAppointment.java
  src/main/java/seedu/address/model/appointment/UniqueAppointmentList.java
  src/main/java/seedu/address/model/person/client/Client.java
  src/main/java/seedu/address/model/person/hairdresser/Hairdresser.java
  src/main/java/seedu/address/storage/JsonAdaptedAppointment.java
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Task

#176 Add Filter feature for client, hairdresser, and appointment classes
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/CollectionUtil.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commandalias/CommandWord.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/appointment/FilterAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/client/FilterClientCommand.java
  src/main/java/seedu/address/logic/commands/hairdresser/FilterHairdresserCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/appointment/FilterAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/client/FilterClientCommandParser.java
  src/main/java/seedu/address/logic/parser/hairdresser/FilterHairdresserCommandParser.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/client/ClientNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/hairdresser/HairdresserNameContainsKeywordsPredicate.java
Labels: type.Task

#194 Refactor UG client section
  docs/UserGuide.md
  docs/images/AddClientOutcome.png
  docs/images/DeleteClientOutcome.png
  docs/images/EditClientOutcome.png
  docs/images/FilterClientOutcome.png
Labels: documentation

#216 fix ug bugs
  docs/UserGuide.md
Labels: bug, documentation

#250 update ui
  src/main/java/seedu/address/ui/appointment/AppointmentCard.java
  src/main/java/seedu/address/ui/client/ClientCard.java
  src/main/java/seedu/address/ui/hairdresser/HairdresserCard.java
  src/main/resources/images/appt.png
  src/main/resources/images/client.png
  src/main/resources/images/hairdresser.png
  src/main/resources/view/AppointmentListCard.fxml
  src/main/resources/view/ClientListCard.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HairdresserListCard.fxml
  src/main/resources/view/MainWindow.fxml
Labels: severity.Low, type.Task
